
name: CI
on:
   push:
   schedule:
    - cron: '1/1 * * * *'    
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: commit
      run: |
        git config --global user.email yanxia_he@126.com
        git config --global user.name Yanxiall
        git add .
        git commit -m "update" -a	
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
